// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConnectDB.Migrations
{
    [DbContext(typeof(ConDB))]
    partial class ConDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Data.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Article")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("InAktau")
                        .HasColumnType("int");

                    b.Property<int>("InAlmata")
                        .HasColumnType("int");

                    b.Property<int>("InAstana")
                        .HasColumnType("int");

                    b.Property<double>("InputPrice")
                        .HasColumnType("double");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<double>("RecomPrice")
                        .HasColumnType("double");

                    b.Property<string>("RegNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("WarehousePlace")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Warehouse");
                });
#pragma warning restore 612, 618
        }
    }
}
